version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing NPM dependencies...
      - npm install
  pre-build:
    commands:
      - echo Pre-build phase
  build:
    command:
      - echo Build phase
  post-build:
    command:
      - echo Build completed on 'date'

artifacts:
  files:
    - '**/*'   #Inclui todos os arquivos e subpastas recursivamente