version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing NPM dependencies...
      - npm install
  pre_build: # Boa prática usar underscore aqui também, embora o hífen seja aceito
    commands:
      - echo Pre-build phase
  build:
    commands:   # <-- CORREÇÃO: 'commands' no plural
      - echo Build phase
  post_build: # <-- CORREÇÃO: 'post_build' com underscore
    commands:   # <-- CORREÇÃO: 'commands' no plural
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'    # Inclui todos os arquivos e subpastas recursivamente
